-- Table: public.support_cases_normalized

-- DROP TABLE public.support_cases_normalized;

CREATE TABLE public.support_cases_normalized_expanded
(
    "CASE_NUMBER" integer NOT NULL,
    "SUBJECT" character varying(255) COLLATE pg_catalog."default",
    "STATUS" character varying(50) COLLATE pg_catalog."default",
    "PRIORITY" character varying(20) COLLATE pg_catalog."default",
    "SEVERITY" character varying(20) COLLATE pg_catalog."default",
    "OWNER" character varying(100) COLLATE pg_catalog."default",
    "OWNER_TYPE" character varying(5) COLLATE pg_catalog."default",
    "OWNER_MANAGER" character varying(100) COLLATE pg_catalog."default",
    "DATE_CREATED" timestamp(0) without time zone,
    "PRIMARY_QUEUE" character varying(50) COLLATE pg_catalog."default",
    "ACCOUNT_NAME" character varying(100) COLLATE pg_catalog."default",
    "CUSTOMER_NAME" character varying(100) COLLATE pg_catalog."default",
    "CONTACT_NAME" character varying(100) COLLATE pg_catalog."default",
    "PRODUCT_SUITE" character varying(3) COLLATE pg_catalog."default",
    "PRODUCT_NAME" character varying(100) COLLATE pg_catalog."default",
    "PRODUCT_VERSION" character varying(50) COLLATE pg_catalog."default",
    "PRODUCT_AREA" character varying(50) COLLATE pg_catalog."default",
    "DATE_LAST_MODIFIED" timestamp(0) without time zone,
    "DATE_LAST_PUBLIC_COMMENT__INBOUND_OR_OUTBOUND_" timestamp(0) without time zone,
    "DATE_LAST_OUTBOUND_PUBLIC_COMMENT" timestamp(0) without time zone,
    "DATE_LAST_CUSTOMER_COMMENT" timestamp(0) without time zone,
    "DATE_WAITING_FOR_CUSTOMER_SINCE" timestamp(0) without time zone,
    "DATE_ASSIGNED" timestamp(0) without time zone,
    "DATE_CLOSED" timestamp(0) without time zone,
    "DATE_CLOSED__DATE_" timestamp(0) without time zone,
    "REASON" character varying(50) COLLATE pg_catalog."default",
    "SUB_REASON" character varying(50) COLLATE pg_catalog."default",
    "HOT_FIX_REQUEST" character varying(10) COLLATE pg_catalog."default",
    "TIMES_HOT_FIX_WAS_REJECTED" character varying(10) COLLATE pg_catalog."default",
    "OTHER_PRODUCT_INFO" character varying(50) COLLATE pg_catalog."default",
    "MARK_FOR_KB_ARTICLE" character varying(10) COLLATE pg_catalog."default",
    "OS" character varying(50) COLLATE pg_catalog."default",
    "HARDWARE" character varying(50) COLLATE pg_catalog."default",
    "ENVIRONMENT_TYPE" character varying(50) COLLATE pg_catalog."default",
    "VIRTUALIZED_PLATFORM" character varying(25) COLLATE pg_catalog."default",
    "CONTACT_EMAIL" character varying(100) COLLATE pg_catalog."default",
    "CONTACT_PHONE" character varying(50) COLLATE pg_catalog."default",
    "CONTACT_STATE" character varying(50) COLLATE pg_catalog."default",
    "CONTACT_COUNTRY" character varying(50) COLLATE pg_catalog."default",
    "CONTACT_TIMEZONE" character varying(50) COLLATE pg_catalog."default",
    "EMAIL_CC_LIST" character varying(1024) COLLATE pg_catalog."default",
    "ACCOUNT_STATE" character varying(50) COLLATE pg_catalog."default",
    "ACCOUNT_COUNTRY" character varying(50) COLLATE pg_catalog."default",
    "ENTITLEMENT_SUPPORT_LEVEL" character varying(25) COLLATE pg_catalog."default",
    "ENTITLEMENT_TEXT" character varying(100) COLLATE pg_catalog."default",
    "ENTITLEMENT_STATUS" character varying(25) COLLATE pg_catalog."default",
    "ACCOUNT_AT_RISK" character varying(25) COLLATE pg_catalog."default",
    "ACCOUNT_TYPE" character varying(50) COLLATE pg_catalog."default",
    "ACCOUNT_ORACLE_ID" integer,
    "INITIAL_RESPONSE_SEVERITY" character varying(25) COLLATE pg_catalog."default",
    "MAXIMUM_ATTAINED_SEVERITY" character varying(25) COLLATE pg_catalog."default",
    "INITIAL_RESPONSE_TIME" double precision,
    "INITIAL_RESPONSE_MINUTES" integer,
    "NO_OF_PUBLIC_UPDATES" character varying(10) COLLATE pg_catalog."default",
    "NO_OF_PRIVATE_UPDATES" character varying(10) COLLATE pg_catalog."default",
    "NO_OF_LINKED_JIRAS" character varying(10) COLLATE pg_catalog."default",
    "NO_OF_LINKED_KBAS" character varying(10) COLLATE pg_catalog."default",
    "ACTIVE_HOURS" double precision,
    "SUPPORT_HOURS" double precision,
    "OPEN_HOURS" double precision,
    "AWAIT_CUSTOMER_HOURS" double precision,
    "IN_DEV_HOURS" double precision,
    "WORKING_WITH_OPS_HOURS" double precision,
    "AWAIT_VENDOR_HOURS" double precision,
    "AWAIT_VENDOR_FIX_HOURS" double precision,
    "AWAIT_HARDWARE_RETURN_HOURS" double precision,
    "DEFECT_ENH_SUBMITTED_HOURS" double precision,
    "PENDING_CLIENT_VERIFICATION_HOURS" double precision,
    "AWAIT_ENHANCEMENT_HOURS" character varying(10) COLLATE pg_catalog."default",
    "AWAIT_DEV_FIX_HOURS" character varying(10) COLLATE pg_catalog."default",
    "SEV_1_HOURS" double precision,
    "SEV_2_HOURS" double precision,
    "SEV_3_HOURS" double precision,
    "SEV_4_HOURS" double precision,
    "CUSTOMER_REGION" character varying(50) COLLATE pg_catalog."default",
    "CASE_ORIGIN" character varying(50) COLLATE pg_catalog."default",
    "LEGACY_TSC_ID" integer,
    "CUSTOMER_ESCALATED" character varying(25) COLLATE pg_catalog."default",
    "CUSTOMER_ESC_DATE" timestamp(0) without time zone,
    "CUSTOMER_ESC_SOURCE" character varying(50) COLLATE pg_catalog."default",
    "CUSTOMER_ESC_REASON" character varying(50) COLLATE pg_catalog."default",
    "REPORT_DATE" timestamp(0) without time zone,
    "REFERRED_TO_CUSTOMER_SUCCESS" character varying(10) COLLATE pg_catalog."default",
    "ACTIVE_DAYS" double precision,
    "DATE_PRIORITY_CHANGED" timestamp(0) without time zone,
    "CASE_PRIORITY_RAISED" character varying(10) COLLATE pg_catalog."default",
    "INITIAL_CASE_PRIORITY" character varying(25) COLLATE pg_catalog."default",
    "TYPE_OF_ENGAGEMENT" character varying(25) COLLATE pg_catalog."default",
    "INITIAL_RESPONSE_SLA_VIOLATED__C" character varying(25) COLLATE pg_catalog."default",
    "ASM" character varying(100) COLLATE pg_catalog."default",
    "ASM_S_MANGER" character varying(100) COLLATE pg_catalog."default",
    "JIRA_CREATED_DATE" timestamp(0) without time zone,
    "JIRA_ASSIGNEE" character varying(255) COLLATE pg_catalog."default",
    "JIRA_STATUS" character varying(50) COLLATE pg_catalog."default",
    "JIRA_ID" character varying(100) COLLATE pg_catalog."default",
    "JIRA_TYPE" character varying(255) COLLATE pg_catalog."default",
    "JIRA_SEVERITY" character varying(50) COLLATE pg_catalog."default",
    "JIRA_RESOLUTION" character varying(100) COLLATE pg_catalog."default",
    "JIRA_FIX_VERSION" character varying(512) COLLATE pg_catalog."default",
    "JIRA_PRIORITY" character varying(50) COLLATE pg_catalog."default",
    "JIRA_UPDATED_DATE" timestamp(0) without time zone,
    CONSTRAINT pk_case_number_n PRIMARY KEY ("CASE_NUMBER")
)

TABLESPACE pg_default;

ALTER TABLE public.support_cases_normalized_expanded
    OWNER to webfocus;